name: little_farmer
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_floating_bottom_bar: ^1.3.0
  video_player: ^2.10.1
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  http: ^1.6.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  firebase_database: ^12.1.0
  firebase_core: ^4.2.1
  flutter_launcher_icons: ^0.14.4
  country_picker: ^2.0.27
  synchronized: ^3.4.0
  flutter_device_type: ^0.4.0
  flutter_widget_from_html: ^0.17.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.2.3
  external_path: ^2.2.0
  share_plus: ^10.1.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/desktop_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/desktop_logo.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
          weight: 900
    - family: SourceSerif4
      fonts:
        - asset: fonts/SourceSerif4-Regular.ttf
          weight: 900
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
          weight: 400
